### ISSUE TITLE
Tested OS

### ISSUE THREAD

**Issue by firefly-cpp** [Infineon/StreamGen#5]
Is there any evidence that the software works on most major operating systems? Maybe you can add a line stating where this has already been tested in a similar style as outlined here: https://github.com/firefly-cpp/NiaAML

This issue is a part of the review process: openjournals/joss-reviews#7206

**Comment by LaurenzBeck** [comment]
I don't think there should be surprises since most dependencies are pure Python ones 🤔

I already tested on windows locally and the CI runs on an ubuntu machine.
I will have a look if I can include different operating systems in the CI test matrix.

Thanks for the hint Iztok 🙏

**Comment by LaurenzBeck** [comment]
I added runners for windows and macOs :)

No surprises there 🎉

**Comment by hoanganhngo610** [comment]
Same results here. I tried installing on both Windows and MacOS, both running perfectly fine!
